float:
  any:
  - base_args: ['@metric']
    constructor: PGVector_Remote
    disabled: false
    docker_tag: ann-benchmarks-pgvector_remote
    module: ann_benchmarks.algorithms.pgvector_remote
    name: pgvector_remote
    run_groups:
      rungroup-1:
        arg_groups: [{}]
        args: {}
        query_args: [[]]
